<a href="https://colab.research.google.com/github/harishkumar77/ML_20BRS1231/blob/main/20BRS1231_MLLAB_11_SLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv('/content/data.csv')
data.head(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
data['diagnosis'].replace({'M':1,'B':0}, inplace = True)
data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,1,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,1,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,1,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,1,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,0,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [ ]:
X = data['fractal_dimension_worst']
y = data.drop(['fractal_dimension_worst'],axis=1)

In [ ]:
X

0      0.11890
1      0.08902
2      0.08758
3      0.17300
4      0.07678
        ...
564    0.07115
565    0.06637
566    0.07820
567    0.12400
568    0.07039
Name: fractal_dimension_worst, Length: 569, dtype: float64

In [ ]:
y

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,Unnamed: 32
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,NaN
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,NaN
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,NaN
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,NaN
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,1,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,NaN
565,926682,1,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,NaN
566,926954,1,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,NaN
567,927241,1,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,NaN
568,92751,0,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,NaN

In [ ]:
y = np.nan_to_num(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
len(X_train)

381

In [ ]:
import tensorflow

In [ ]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Activation, Dense 
import tensorflow.keras as tfk
model = Sequential() 
initializer=tfk.initializers.Ones()
layer_1 = Dense(1, input_shape = (1,),kernel_initializer=initializer,bias_initializer=initializer) 
# layer2=Dense(1)
model.add(layer_1) 
# model.add(layer2)
opt = tfk.optimizers.Adam(learning_rate=0.01)
model.compile(loss=tensorflow.keras.losses.MeanSquaredError(),optimizer=opt)

In [ ]:
history=model.fit(X_train,y_train,epochs=50,batch_size=8)

Epoch 1/50
48/48 [==============================] - 0s 1ms/step - loss: 553884854517760.0000
Epoch 2/50
48/48 [==============================] - 0s 1ms/step - loss: 553884787408896.0000
Epoch 3/50
48/48 [==============================] - 0s 1ms/step - loss: 553884720300032.0000
Epoch 4/50
48/48 [==============================] - 0s 2ms/step - loss: 553884888072192.0000
Epoch 5/50
48/48 [==============================] - 0s 1ms/step - loss: 553884787408896.0000
Epoch 6/50
48/48 [==============================] - 0s 1ms/step - loss: 553884854517760.0000
Epoch 7/50
48/48 [==============================] - 0s 1ms/step - loss: 553884787408896.0000
Epoch 8/50
48/48 [==============================] - 0s 1ms/step - loss: 553884854517760.0000
Epoch 9/50
48/48 [==============================] - 0s 2ms/step - loss: 553884753854464.0000
Epoch 10/50
48/48 [==============================] - 0s 2ms/step - loss: 553884854517760.0000
Epoch 11/50
48/48 [==============================] - 0s 1ms/step - loss: 553884854517760.0000
Epoch 12/50
48/48 [==============================] - 0s 2ms/step - loss: 553884787408896.0000
Epoch 13/50
48/48 [==============================] - 0s 2ms/step - loss: 553884854517760.0000
Epoch 14/50
48/48 [==============================] - 0s 2ms/step - loss: 553884854517760.0000
Epoch 15/50
48/48 [==============================] - 0s 1ms/step - loss: 553884753854464.0000
Epoch 16/50
48/48 [==============================] - 0s 1ms/step - loss: 553884720300032.0000
Epoch 17/50
48/48 [==============================] - 0s 2ms/step - loss: 553884787408896.0000
Epoch 18/50
48/48 [==============================] - 0s 1ms/step - loss: 553884720300032.0000
Epoch 19/50
48/48 [==============================] - 0s 2ms/step - loss: 553884753854464.0000
Epoch 20/50
48/48 [==============================] - 0s 1ms/step - loss: 553884787408896.0000
Epoch 21/50
48/48 [==============================] - 0s 1ms/step - loss: 553884787408896.0000
Epoch 22/50
48/48 [==============================] - 0s 2ms/step - loss: 553884787408896.0000
Epoch 23/50
48/48 [==============================] - 0s 1ms/step - loss: 553884787408896.0000
Epoch 24/50
48/48 [==============================] - 0s 1ms/step - loss: 553884854517760.0000
Epoch 25/50
48/48 [==============================] - 0s 1ms/step - loss: 553884653191168.0000
Epoch 26/50
48/48 [==============================] - 0s 2ms/step - loss: 553884753854464.0000
Epoch 27/50
48/48 [==============================] - 0s 1ms/step - loss: 553884787408896.0000
Epoch 28/50
48/48 [==============================] - 0s 1ms/step - loss: 553884753854464.0000
Epoch 29/50
48/48 [==============================] - 0s 1ms/step - loss: 553884854517760.0000
Epoch 30/50
48/48 [==============================] - 0s 1ms/step - loss: 553884921626624.0000
Epoch 31/50
48/48 [==============================] - 0s 2ms/step - loss: 553884753854464.0000
Epoch 32/50
48/48 [==============================] - 0s 1ms/step - loss: 553884854517760.0000
Epoch 33/50
48/48 [==============================] - 0s 1ms/step - loss: 553884787408896.0000
Epoch 34/50
48/48 [==============================] - 0s 1ms/step - loss: 553884720300032.0000
Epoch 35/50
48/48 [==============================] - 0s 2ms/step - loss: 553884854517760.0000
Epoch 36/50
48/48 [==============================] - 0s 2ms/step - loss: 553884888072192.0000
Epoch 37/50
48/48 [==============================] - 0s 1ms/step - loss: 553884787408896.0000
Epoch 38/50
48/48 [==============================] - 0s 1ms/step - loss: 553884753854464.0000
Epoch 39/50
48/48 [==============================] - 0s 1ms/step - loss: 553884787408896.0000
Epoch 40/50
48/48 [==============================] - 0s 1ms/step - loss: 553884888072192.0000
Epoch 41/50
48/48 [==============================] - 0s 1ms/step - loss: 553884753854464.0000
Epoch 42/50
48/48 [==============================] - 0s 1ms/step - loss: 553884653191168.0000
Epoch 43/50
48/48 [==============================] - 0s 1ms/step - loss: 553884787408896.0000
Epoch 44/50
48/48 [==============================] - 0s 1ms/step - loss: 553884720300032.0000
Epoch 45/50
48/48 [==============================] - 0s 1ms/step - loss: 553884854517760.0000
Epoch 46/50
48/48 [==============================] - 0s 1ms/step - loss: 553884854517760.0000
Epoch 47/50
48/48 [==============================] - 0s 1ms/step - loss: 553884787408896.0000
Epoch 48/50
48/48 [==============================] - 0s 2ms/step - loss: 553884753854464.0000
Epoch 49/50
48/48 [==============================] - 0s 2ms/step - loss: 553884753854464.0000
Epoch 50/50
48/48 [==============================] - 0s 2ms/step - loss: 553884854517760.0000

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
y_pred = model.predict(X_test).sum(axis=1)

6/6 [==============================] - 0s 2ms/step

In [ ]:
len(y_test)

188

In [ ]:
len(y_pred)

188

In [ ]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
r2_score(y_test, y_pred)

ValueError: ignored